[package]
name = "inkos-android"
version = "0.1.0"
authors = ["SufremOak <migsufrem@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "inkos-android-desktop"
path = "gen/bin/desktop.rs"

[dependencies]
futures = "0.3.8"
mobile-entry-point = "0.1.0"
wgpu = "0.6.0"
winit = "0.23.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.9.0"
log = "0.4.11"
ndk-glue = "0.2.1"

[target.'cfg(not(target_os = "android"))'.dependencies]
wgpu-subscriber = "0.1.0"
